name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: maven Testing
        run: mvn Testing

      - name: checkstyle
        run: mvn checkstyle:checkstyle    
